# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs

__all__ = [
    'GetGroupMembersResult',
    'AwaitableGetGroupMembersResult',
    'get_group_members',
    'get_group_members_output',
]

@pulumi.output_type
class GetGroupMembersResult:
    """
    A collection of values returned by getGroupMembers.
    """
    def __init__(__self__, etag=None, group_id=None, id=None, include_derived_membership=None, members=None):
        if etag and not isinstance(etag, str):
            raise TypeError("Expected argument 'etag' to be a str")
        pulumi.set(__self__, "etag", etag)
        if group_id and not isinstance(group_id, str):
            raise TypeError("Expected argument 'group_id' to be a str")
        pulumi.set(__self__, "group_id", group_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if include_derived_membership and not isinstance(include_derived_membership, bool):
            raise TypeError("Expected argument 'include_derived_membership' to be a bool")
        pulumi.set(__self__, "include_derived_membership", include_derived_membership)
        if members and not isinstance(members, list):
            raise TypeError("Expected argument 'members' to be a list")
        pulumi.set(__self__, "members", members)

    @property
    @pulumi.getter
    def etag(self) -> str:
        """
        ETag of the resource.
        """
        return pulumi.get(self, "etag")

    @property
    @pulumi.getter(name="groupId")
    def group_id(self) -> str:
        """
        Identifies the group in the API request. The value can be the group's email address, group alias, or the unique group ID.
        """
        return pulumi.get(self, "group_id")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The ID of this resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="includeDerivedMembership")
    def include_derived_membership(self) -> Optional[bool]:
        """
        If true, lists indirect group memberships
        """
        return pulumi.get(self, "include_derived_membership")

    @property
    @pulumi.getter
    def members(self) -> Sequence['outputs.GetGroupMembersMemberResult']:
        """
        The members of the group
        """
        return pulumi.get(self, "members")


class AwaitableGetGroupMembersResult(GetGroupMembersResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetGroupMembersResult(
            etag=self.etag,
            group_id=self.group_id,
            id=self.id,
            include_derived_membership=self.include_derived_membership,
            members=self.members)


def get_group_members(group_id: Optional[str] = None,
                      include_derived_membership: Optional[bool] = None,
                      opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetGroupMembersResult:
    """
    ## Example Usage

    ```python
    import pulumi
    import pulumi_googleworkspace as googleworkspace

    sales_group = googleworkspace.get_group(email="sales@example.com")
    sales_group_members = googleworkspace.get_group_members(group_id=sales_group.id)
    pulumi.export("groupMembers", sales_group_members.members)
    ```


    :param str group_id: Identifies the group in the API request. The value can be the group's email address, group alias, or the unique group ID.
    :param bool include_derived_membership: If true, lists indirect group memberships
    """
    __args__ = dict()
    __args__['groupId'] = group_id
    __args__['includeDerivedMembership'] = include_derived_membership
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('googleworkspace:index/getGroupMembers:getGroupMembers', __args__, opts=opts, typ=GetGroupMembersResult).value

    return AwaitableGetGroupMembersResult(
        etag=__ret__.etag,
        group_id=__ret__.group_id,
        id=__ret__.id,
        include_derived_membership=__ret__.include_derived_membership,
        members=__ret__.members)


@_utilities.lift_output_func(get_group_members)
def get_group_members_output(group_id: Optional[pulumi.Input[str]] = None,
                             include_derived_membership: Optional[pulumi.Input[Optional[bool]]] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetGroupMembersResult]:
    """
    ## Example Usage

    ```python
    import pulumi
    import pulumi_googleworkspace as googleworkspace

    sales_group = googleworkspace.get_group(email="sales@example.com")
    sales_group_members = googleworkspace.get_group_members(group_id=sales_group.id)
    pulumi.export("groupMembers", sales_group_members.members)
    ```


    :param str group_id: Identifies the group in the API request. The value can be the group's email address, group alias, or the unique group ID.
    :param bool include_derived_membership: If true, lists indirect group memberships
    """
    ...
