// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace.Outputs
{

    [OutputType]
    public sealed class GetChromePolicySchemaAdditionalTargetKeyNameResult
    {
        public readonly string Key;
        public readonly string KeyDescription;

        [OutputConstructor]
        private GetChromePolicySchemaAdditionalTargetKeyNameResult(
            string key,

            string keyDescription)
        {
            Key = key;
            KeyDescription = keyDescription;
        }
    }
}
