// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace.Outputs
{

    [OutputType]
    public sealed class GetChromePolicySchemaDefinitionEnumTypeResult
    {
        public readonly string Name;
        public readonly ImmutableArray<Outputs.GetChromePolicySchemaDefinitionEnumTypeValueResult> Values;

        [OutputConstructor]
        private GetChromePolicySchemaDefinitionEnumTypeResult(
            string name,

            ImmutableArray<Outputs.GetChromePolicySchemaDefinitionEnumTypeValueResult> values)
        {
            Name = name;
            Values = values;
        }
    }
}
