// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace.Outputs
{

    [OutputType]
    public sealed class GetUsersUserResult
    {
        public readonly ImmutableArray<Outputs.GetUsersUserAddressResult> Addresses;
        public readonly bool AgreedToTerms;
        public readonly ImmutableArray<string> Aliases;
        public readonly bool Archived;
        public readonly bool ChangePasswordAtNextLogin;
        public readonly string CreationTime;
        public readonly ImmutableArray<Outputs.GetUsersUserCustomSchemaResult> CustomSchemas;
        public readonly string CustomerId;
        public readonly string DeletionTime;
        public readonly ImmutableArray<Outputs.GetUsersUserEmailResult> Emails;
        public readonly string Etag;
        public readonly ImmutableArray<Outputs.GetUsersUserExternalIdResult> ExternalIds;
        public readonly string HashFunction;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetUsersUserImResult> Ims;
        public readonly bool IncludeInGlobalAddressList;
        public readonly bool IpAllowlist;
        public readonly bool IsAdmin;
        public readonly bool IsDelegatedAdmin;
        public readonly bool IsEnforcedIn2StepVerification;
        public readonly bool IsEnrolledIn2StepVerification;
        public readonly bool IsMailboxSetup;
        public readonly ImmutableArray<Outputs.GetUsersUserKeywordResult> Keywords;
        public readonly ImmutableArray<Outputs.GetUsersUserLanguageResult> Languages;
        public readonly string LastLoginTime;
        public readonly ImmutableArray<Outputs.GetUsersUserLocationResult> Locations;
        public readonly ImmutableArray<Outputs.GetUsersUserNameResult> Names;
        public readonly ImmutableArray<string> NonEditableAliases;
        public readonly string OrgUnitPath;
        public readonly ImmutableArray<Outputs.GetUsersUserOrganizationResult> Organizations;
        public readonly string Password;
        public readonly ImmutableArray<Outputs.GetUsersUserPhoneResult> Phones;
        public readonly ImmutableArray<Outputs.GetUsersUserPosixAccountResult> PosixAccounts;
        public readonly string PrimaryEmail;
        public readonly string RecoveryEmail;
        public readonly string RecoveryPhone;
        public readonly ImmutableArray<Outputs.GetUsersUserRelationResult> Relations;
        public readonly ImmutableArray<Outputs.GetUsersUserSshPublicKeyResult> SshPublicKeys;
        public readonly bool Suspended;
        public readonly string SuspensionReason;
        public readonly string ThumbnailPhotoEtag;
        public readonly string ThumbnailPhotoUrl;
        public readonly ImmutableArray<Outputs.GetUsersUserWebsiteResult> Websites;

        [OutputConstructor]
        private GetUsersUserResult(
            ImmutableArray<Outputs.GetUsersUserAddressResult> addresses,

            bool agreedToTerms,

            ImmutableArray<string> aliases,

            bool archived,

            bool changePasswordAtNextLogin,

            string creationTime,

            ImmutableArray<Outputs.GetUsersUserCustomSchemaResult> customSchemas,

            string customerId,

            string deletionTime,

            ImmutableArray<Outputs.GetUsersUserEmailResult> emails,

            string etag,

            ImmutableArray<Outputs.GetUsersUserExternalIdResult> externalIds,

            string hashFunction,

            string id,

            ImmutableArray<Outputs.GetUsersUserImResult> ims,

            bool includeInGlobalAddressList,

            bool ipAllowlist,

            bool isAdmin,

            bool isDelegatedAdmin,

            bool isEnforcedIn2StepVerification,

            bool isEnrolledIn2StepVerification,

            bool isMailboxSetup,

            ImmutableArray<Outputs.GetUsersUserKeywordResult> keywords,

            ImmutableArray<Outputs.GetUsersUserLanguageResult> languages,

            string lastLoginTime,

            ImmutableArray<Outputs.GetUsersUserLocationResult> locations,

            ImmutableArray<Outputs.GetUsersUserNameResult> names,

            ImmutableArray<string> nonEditableAliases,

            string orgUnitPath,

            ImmutableArray<Outputs.GetUsersUserOrganizationResult> organizations,

            string password,

            ImmutableArray<Outputs.GetUsersUserPhoneResult> phones,

            ImmutableArray<Outputs.GetUsersUserPosixAccountResult> posixAccounts,

            string primaryEmail,

            string recoveryEmail,

            string recoveryPhone,

            ImmutableArray<Outputs.GetUsersUserRelationResult> relations,

            ImmutableArray<Outputs.GetUsersUserSshPublicKeyResult> sshPublicKeys,

            bool suspended,

            string suspensionReason,

            string thumbnailPhotoEtag,

            string thumbnailPhotoUrl,

            ImmutableArray<Outputs.GetUsersUserWebsiteResult> websites)
        {
            Addresses = addresses;
            AgreedToTerms = agreedToTerms;
            Aliases = aliases;
            Archived = archived;
            ChangePasswordAtNextLogin = changePasswordAtNextLogin;
            CreationTime = creationTime;
            CustomSchemas = customSchemas;
            CustomerId = customerId;
            DeletionTime = deletionTime;
            Emails = emails;
            Etag = etag;
            ExternalIds = externalIds;
            HashFunction = hashFunction;
            Id = id;
            Ims = ims;
            IncludeInGlobalAddressList = includeInGlobalAddressList;
            IpAllowlist = ipAllowlist;
            IsAdmin = isAdmin;
            IsDelegatedAdmin = isDelegatedAdmin;
            IsEnforcedIn2StepVerification = isEnforcedIn2StepVerification;
            IsEnrolledIn2StepVerification = isEnrolledIn2StepVerification;
            IsMailboxSetup = isMailboxSetup;
            Keywords = keywords;
            Languages = languages;
            LastLoginTime = lastLoginTime;
            Locations = locations;
            Names = names;
            NonEditableAliases = nonEditableAliases;
            OrgUnitPath = orgUnitPath;
            Organizations = organizations;
            Password = password;
            Phones = phones;
            PosixAccounts = posixAccounts;
            PrimaryEmail = primaryEmail;
            RecoveryEmail = recoveryEmail;
            RecoveryPhone = recoveryPhone;
            Relations = relations;
            SshPublicKeys = sshPublicKeys;
            Suspended = suspended;
            SuspensionReason = suspensionReason;
            ThumbnailPhotoEtag = thumbnailPhotoEtag;
            ThumbnailPhotoUrl = thumbnailPhotoUrl;
            Websites = websites;
        }
    }
}
