// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace.Outputs
{

    [OutputType]
    public sealed class GmailSendAsAliasSmtpMsa
    {
        /// <summary>
        /// The hostname of the SMTP service.
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// The password that will be used for authentication with the SMTP service. This is a write-only field that can be specified in requests to create or update SendAs settings; it is never populated in responses.
        /// </summary>
        public readonly string? Password;
        /// <summary>
        /// The port of the SMTP service.
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// Defaults to `securityModeUnspecified`. The protocol that will be used to secure communication with the SMTP service.
        /// </summary>
        public readonly string? SecurityMode;
        /// <summary>
        /// The username that will be used for authentication with the SMTP service. This is a write-only field that can be specified in requests to create or update SendAs settings; it is never populated in responses.
        /// </summary>
        public readonly string? Username;

        [OutputConstructor]
        private GmailSendAsAliasSmtpMsa(
            string host,

            string? password,

            int port,

            string? securityMode,

            string? username)
        {
            Host = host;
            Password = password;
            Port = port;
            SecurityMode = securityMode;
            Username = username;
        }
    }
}
