// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace.Outputs
{

    [OutputType]
    public sealed class SchemaField
    {
        public readonly string? DisplayName;
        public readonly string? Etag;
        public readonly string? FieldId;
        public readonly string FieldName;
        public readonly string FieldType;
        public readonly bool? Indexed;
        public readonly bool? MultiValued;
        public readonly Outputs.SchemaFieldNumericIndexingSpec? NumericIndexingSpec;
        public readonly string? ReadAccessType;

        [OutputConstructor]
        private SchemaField(
            string? displayName,

            string? etag,

            string? fieldId,

            string fieldName,

            string fieldType,

            bool? indexed,

            bool? multiValued,

            Outputs.SchemaFieldNumericIndexingSpec? numericIndexingSpec,

            string? readAccessType)
        {
            DisplayName = displayName;
            Etag = etag;
            FieldId = fieldId;
            FieldName = fieldName;
            FieldType = fieldType;
            Indexed = indexed;
            MultiValued = multiValued;
            NumericIndexingSpec = numericIndexingSpec;
            ReadAccessType = readAccessType;
        }
    }
}
