// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace.Outputs
{

    [OutputType]
    public sealed class UserName
    {
        public readonly string FamilyName;
        public readonly string? FullName;
        public readonly string? GivenName;

        [OutputConstructor]
        private UserName(
            string familyName,

            string? fullName,

            string? givenName)
        {
            FamilyName = familyName;
            FullName = fullName;
            GivenName = givenName;
        }
    }
}
