// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package googleworkspace

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-googleworkspace/sdk/go/googleworkspace"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		example, err := googleworkspace.LookupUser(ctx, &GetUserArgs{
// 			PrimaryEmail: pulumi.StringRef("user.with.gmail.license@example.com"),
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		alias, err := googleworkspace.NewUser(ctx, "alias", &googleworkspace.UserArgs{
// 			PrimaryEmail: pulumi.String("alias@example.com"),
// 			Password:     pulumi.String("34819d7beeabb9260a5c854bc85b3e44"),
// 			HashFunction: pulumi.String("MD5"),
// 			Name: &UserNameArgs{
// 				FamilyName: pulumi.String("Scott"),
// 				GivenName:  pulumi.String("Michael"),
// 			},
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		_, err = googleworkspace.NewGmailSendAsAlias(ctx, "test", &googleworkspace.GmailSendAsAliasArgs{
// 			PrimaryEmail: pulumi.String(example.PrimaryEmail),
// 			SendAsEmail:  alias.PrimaryEmail,
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// ## Import
//
// ```sh
//  $ pulumi import googleworkspace:index/gmailSendAsAlias:GmailSendAsAlias alias user@example.com:alias@anotherexample.com
// ```
type GmailSendAsAlias struct {
	pulumi.CustomResourceState

	// A name that appears in the 'From:' header for mail sent using this alias. For custom 'from' addresses, when this is empty, Gmail will populate the 'From:' header with the name that is used for the primary address associated with the account. If the admin has disabled the ability for users to update their name format, requests to update this field for the primary login will silently fail.
	DisplayName pulumi.StringPtrOutput `pulumi:"displayName"`
	// Whether this address is selected as the default 'From:' address in situations such as composing a new message or sending
	// a vacation auto-reply. Every Gmail account has exactly one default send-as address, so the only legal value that clients
	// may write to this field is true. Changing this from false to true for an address will result in this field becoming
	// false for the other previous default address. Toggling an existing alias' default to false is not possible, another
	// alias must be added/imported and toggled to true to remove the default from an existing alias. To avoid drift with
	// Terraform, please change the previous default's config to false AFTER a new default is applied and perform a refresh to
	// synchronize with remote state.
	IsDefault pulumi.BoolPtrOutput `pulumi:"isDefault"`
	// Whether this address is the primary address used to login to the account. Every Gmail account has exactly one primary address, and it cannot be deleted from the collection of send-as aliases.
	IsPrimary pulumi.BoolOutput `pulumi:"isPrimary"`
	// User's primary email address.
	PrimaryEmail pulumi.StringOutput `pulumi:"primaryEmail"`
	// An optional email address that is included in a 'Reply-To:' header for mail sent using this alias. If this is empty, Gmail will not generate a 'Reply-To:' header.
	ReplyToAddress pulumi.StringPtrOutput `pulumi:"replyToAddress"`
	// The email address that appears in the 'From:' header for mail sent using this alias.
	SendAsEmail pulumi.StringOutput `pulumi:"sendAsEmail"`
	// An optional HTML signature that is included in messages composed with this alias in the Gmail web UI. This signature is added to new emails only.
	Signature pulumi.StringPtrOutput `pulumi:"signature"`
	// An optional SMTP service that will be used as an outbound relay for mail sent using this alias. If this is empty, outbound mail will be sent directly from Gmail's servers to the destination SMTP service. This setting only applies to custom 'from' aliases.
	SmtpMsa GmailSendAsAliasSmtpMsaPtrOutput `pulumi:"smtpMsa"`
	// Defaults to `true`. Whether Gmail should treat this address as an alias for the user's primary email address. This setting only applies to custom 'from' aliases. See https://support.google.com/a/answer/1710338 for help on making this decision
	TreatAsAlias pulumi.BoolPtrOutput `pulumi:"treatAsAlias"`
	// Indicates whether this address has been verified for use as a send-as alias.
	VerificationStatus pulumi.StringOutput `pulumi:"verificationStatus"`
}

// NewGmailSendAsAlias registers a new resource with the given unique name, arguments, and options.
func NewGmailSendAsAlias(ctx *pulumi.Context,
	name string, args *GmailSendAsAliasArgs, opts ...pulumi.ResourceOption) (*GmailSendAsAlias, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PrimaryEmail == nil {
		return nil, errors.New("invalid value for required argument 'PrimaryEmail'")
	}
	if args.SendAsEmail == nil {
		return nil, errors.New("invalid value for required argument 'SendAsEmail'")
	}
	var resource GmailSendAsAlias
	err := ctx.RegisterResource("googleworkspace:index/gmailSendAsAlias:GmailSendAsAlias", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGmailSendAsAlias gets an existing GmailSendAsAlias resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGmailSendAsAlias(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GmailSendAsAliasState, opts ...pulumi.ResourceOption) (*GmailSendAsAlias, error) {
	var resource GmailSendAsAlias
	err := ctx.ReadResource("googleworkspace:index/gmailSendAsAlias:GmailSendAsAlias", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GmailSendAsAlias resources.
type gmailSendAsAliasState struct {
	// A name that appears in the 'From:' header for mail sent using this alias. For custom 'from' addresses, when this is empty, Gmail will populate the 'From:' header with the name that is used for the primary address associated with the account. If the admin has disabled the ability for users to update their name format, requests to update this field for the primary login will silently fail.
	DisplayName *string `pulumi:"displayName"`
	// Whether this address is selected as the default 'From:' address in situations such as composing a new message or sending
	// a vacation auto-reply. Every Gmail account has exactly one default send-as address, so the only legal value that clients
	// may write to this field is true. Changing this from false to true for an address will result in this field becoming
	// false for the other previous default address. Toggling an existing alias' default to false is not possible, another
	// alias must be added/imported and toggled to true to remove the default from an existing alias. To avoid drift with
	// Terraform, please change the previous default's config to false AFTER a new default is applied and perform a refresh to
	// synchronize with remote state.
	IsDefault *bool `pulumi:"isDefault"`
	// Whether this address is the primary address used to login to the account. Every Gmail account has exactly one primary address, and it cannot be deleted from the collection of send-as aliases.
	IsPrimary *bool `pulumi:"isPrimary"`
	// User's primary email address.
	PrimaryEmail *string `pulumi:"primaryEmail"`
	// An optional email address that is included in a 'Reply-To:' header for mail sent using this alias. If this is empty, Gmail will not generate a 'Reply-To:' header.
	ReplyToAddress *string `pulumi:"replyToAddress"`
	// The email address that appears in the 'From:' header for mail sent using this alias.
	SendAsEmail *string `pulumi:"sendAsEmail"`
	// An optional HTML signature that is included in messages composed with this alias in the Gmail web UI. This signature is added to new emails only.
	Signature *string `pulumi:"signature"`
	// An optional SMTP service that will be used as an outbound relay for mail sent using this alias. If this is empty, outbound mail will be sent directly from Gmail's servers to the destination SMTP service. This setting only applies to custom 'from' aliases.
	SmtpMsa *GmailSendAsAliasSmtpMsa `pulumi:"smtpMsa"`
	// Defaults to `true`. Whether Gmail should treat this address as an alias for the user's primary email address. This setting only applies to custom 'from' aliases. See https://support.google.com/a/answer/1710338 for help on making this decision
	TreatAsAlias *bool `pulumi:"treatAsAlias"`
	// Indicates whether this address has been verified for use as a send-as alias.
	VerificationStatus *string `pulumi:"verificationStatus"`
}

type GmailSendAsAliasState struct {
	// A name that appears in the 'From:' header for mail sent using this alias. For custom 'from' addresses, when this is empty, Gmail will populate the 'From:' header with the name that is used for the primary address associated with the account. If the admin has disabled the ability for users to update their name format, requests to update this field for the primary login will silently fail.
	DisplayName pulumi.StringPtrInput
	// Whether this address is selected as the default 'From:' address in situations such as composing a new message or sending
	// a vacation auto-reply. Every Gmail account has exactly one default send-as address, so the only legal value that clients
	// may write to this field is true. Changing this from false to true for an address will result in this field becoming
	// false for the other previous default address. Toggling an existing alias' default to false is not possible, another
	// alias must be added/imported and toggled to true to remove the default from an existing alias. To avoid drift with
	// Terraform, please change the previous default's config to false AFTER a new default is applied and perform a refresh to
	// synchronize with remote state.
	IsDefault pulumi.BoolPtrInput
	// Whether this address is the primary address used to login to the account. Every Gmail account has exactly one primary address, and it cannot be deleted from the collection of send-as aliases.
	IsPrimary pulumi.BoolPtrInput
	// User's primary email address.
	PrimaryEmail pulumi.StringPtrInput
	// An optional email address that is included in a 'Reply-To:' header for mail sent using this alias. If this is empty, Gmail will not generate a 'Reply-To:' header.
	ReplyToAddress pulumi.StringPtrInput
	// The email address that appears in the 'From:' header for mail sent using this alias.
	SendAsEmail pulumi.StringPtrInput
	// An optional HTML signature that is included in messages composed with this alias in the Gmail web UI. This signature is added to new emails only.
	Signature pulumi.StringPtrInput
	// An optional SMTP service that will be used as an outbound relay for mail sent using this alias. If this is empty, outbound mail will be sent directly from Gmail's servers to the destination SMTP service. This setting only applies to custom 'from' aliases.
	SmtpMsa GmailSendAsAliasSmtpMsaPtrInput
	// Defaults to `true`. Whether Gmail should treat this address as an alias for the user's primary email address. This setting only applies to custom 'from' aliases. See https://support.google.com/a/answer/1710338 for help on making this decision
	TreatAsAlias pulumi.BoolPtrInput
	// Indicates whether this address has been verified for use as a send-as alias.
	VerificationStatus pulumi.StringPtrInput
}

func (GmailSendAsAliasState) ElementType() reflect.Type {
	return reflect.TypeOf((*gmailSendAsAliasState)(nil)).Elem()
}

type gmailSendAsAliasArgs struct {
	// A name that appears in the 'From:' header for mail sent using this alias. For custom 'from' addresses, when this is empty, Gmail will populate the 'From:' header with the name that is used for the primary address associated with the account. If the admin has disabled the ability for users to update their name format, requests to update this field for the primary login will silently fail.
	DisplayName *string `pulumi:"displayName"`
	// Whether this address is selected as the default 'From:' address in situations such as composing a new message or sending
	// a vacation auto-reply. Every Gmail account has exactly one default send-as address, so the only legal value that clients
	// may write to this field is true. Changing this from false to true for an address will result in this field becoming
	// false for the other previous default address. Toggling an existing alias' default to false is not possible, another
	// alias must be added/imported and toggled to true to remove the default from an existing alias. To avoid drift with
	// Terraform, please change the previous default's config to false AFTER a new default is applied and perform a refresh to
	// synchronize with remote state.
	IsDefault *bool `pulumi:"isDefault"`
	// User's primary email address.
	PrimaryEmail string `pulumi:"primaryEmail"`
	// An optional email address that is included in a 'Reply-To:' header for mail sent using this alias. If this is empty, Gmail will not generate a 'Reply-To:' header.
	ReplyToAddress *string `pulumi:"replyToAddress"`
	// The email address that appears in the 'From:' header for mail sent using this alias.
	SendAsEmail string `pulumi:"sendAsEmail"`
	// An optional HTML signature that is included in messages composed with this alias in the Gmail web UI. This signature is added to new emails only.
	Signature *string `pulumi:"signature"`
	// An optional SMTP service that will be used as an outbound relay for mail sent using this alias. If this is empty, outbound mail will be sent directly from Gmail's servers to the destination SMTP service. This setting only applies to custom 'from' aliases.
	SmtpMsa *GmailSendAsAliasSmtpMsa `pulumi:"smtpMsa"`
	// Defaults to `true`. Whether Gmail should treat this address as an alias for the user's primary email address. This setting only applies to custom 'from' aliases. See https://support.google.com/a/answer/1710338 for help on making this decision
	TreatAsAlias *bool `pulumi:"treatAsAlias"`
}

// The set of arguments for constructing a GmailSendAsAlias resource.
type GmailSendAsAliasArgs struct {
	// A name that appears in the 'From:' header for mail sent using this alias. For custom 'from' addresses, when this is empty, Gmail will populate the 'From:' header with the name that is used for the primary address associated with the account. If the admin has disabled the ability for users to update their name format, requests to update this field for the primary login will silently fail.
	DisplayName pulumi.StringPtrInput
	// Whether this address is selected as the default 'From:' address in situations such as composing a new message or sending
	// a vacation auto-reply. Every Gmail account has exactly one default send-as address, so the only legal value that clients
	// may write to this field is true. Changing this from false to true for an address will result in this field becoming
	// false for the other previous default address. Toggling an existing alias' default to false is not possible, another
	// alias must be added/imported and toggled to true to remove the default from an existing alias. To avoid drift with
	// Terraform, please change the previous default's config to false AFTER a new default is applied and perform a refresh to
	// synchronize with remote state.
	IsDefault pulumi.BoolPtrInput
	// User's primary email address.
	PrimaryEmail pulumi.StringInput
	// An optional email address that is included in a 'Reply-To:' header for mail sent using this alias. If this is empty, Gmail will not generate a 'Reply-To:' header.
	ReplyToAddress pulumi.StringPtrInput
	// The email address that appears in the 'From:' header for mail sent using this alias.
	SendAsEmail pulumi.StringInput
	// An optional HTML signature that is included in messages composed with this alias in the Gmail web UI. This signature is added to new emails only.
	Signature pulumi.StringPtrInput
	// An optional SMTP service that will be used as an outbound relay for mail sent using this alias. If this is empty, outbound mail will be sent directly from Gmail's servers to the destination SMTP service. This setting only applies to custom 'from' aliases.
	SmtpMsa GmailSendAsAliasSmtpMsaPtrInput
	// Defaults to `true`. Whether Gmail should treat this address as an alias for the user's primary email address. This setting only applies to custom 'from' aliases. See https://support.google.com/a/answer/1710338 for help on making this decision
	TreatAsAlias pulumi.BoolPtrInput
}

func (GmailSendAsAliasArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*gmailSendAsAliasArgs)(nil)).Elem()
}

type GmailSendAsAliasInput interface {
	pulumi.Input

	ToGmailSendAsAliasOutput() GmailSendAsAliasOutput
	ToGmailSendAsAliasOutputWithContext(ctx context.Context) GmailSendAsAliasOutput
}

func (*GmailSendAsAlias) ElementType() reflect.Type {
	return reflect.TypeOf((**GmailSendAsAlias)(nil)).Elem()
}

func (i *GmailSendAsAlias) ToGmailSendAsAliasOutput() GmailSendAsAliasOutput {
	return i.ToGmailSendAsAliasOutputWithContext(context.Background())
}

func (i *GmailSendAsAlias) ToGmailSendAsAliasOutputWithContext(ctx context.Context) GmailSendAsAliasOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GmailSendAsAliasOutput)
}

// GmailSendAsAliasArrayInput is an input type that accepts GmailSendAsAliasArray and GmailSendAsAliasArrayOutput values.
// You can construct a concrete instance of `GmailSendAsAliasArrayInput` via:
//
//          GmailSendAsAliasArray{ GmailSendAsAliasArgs{...} }
type GmailSendAsAliasArrayInput interface {
	pulumi.Input

	ToGmailSendAsAliasArrayOutput() GmailSendAsAliasArrayOutput
	ToGmailSendAsAliasArrayOutputWithContext(context.Context) GmailSendAsAliasArrayOutput
}

type GmailSendAsAliasArray []GmailSendAsAliasInput

func (GmailSendAsAliasArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GmailSendAsAlias)(nil)).Elem()
}

func (i GmailSendAsAliasArray) ToGmailSendAsAliasArrayOutput() GmailSendAsAliasArrayOutput {
	return i.ToGmailSendAsAliasArrayOutputWithContext(context.Background())
}

func (i GmailSendAsAliasArray) ToGmailSendAsAliasArrayOutputWithContext(ctx context.Context) GmailSendAsAliasArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GmailSendAsAliasArrayOutput)
}

// GmailSendAsAliasMapInput is an input type that accepts GmailSendAsAliasMap and GmailSendAsAliasMapOutput values.
// You can construct a concrete instance of `GmailSendAsAliasMapInput` via:
//
//          GmailSendAsAliasMap{ "key": GmailSendAsAliasArgs{...} }
type GmailSendAsAliasMapInput interface {
	pulumi.Input

	ToGmailSendAsAliasMapOutput() GmailSendAsAliasMapOutput
	ToGmailSendAsAliasMapOutputWithContext(context.Context) GmailSendAsAliasMapOutput
}

type GmailSendAsAliasMap map[string]GmailSendAsAliasInput

func (GmailSendAsAliasMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GmailSendAsAlias)(nil)).Elem()
}

func (i GmailSendAsAliasMap) ToGmailSendAsAliasMapOutput() GmailSendAsAliasMapOutput {
	return i.ToGmailSendAsAliasMapOutputWithContext(context.Background())
}

func (i GmailSendAsAliasMap) ToGmailSendAsAliasMapOutputWithContext(ctx context.Context) GmailSendAsAliasMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GmailSendAsAliasMapOutput)
}

type GmailSendAsAliasOutput struct{ *pulumi.OutputState }

func (GmailSendAsAliasOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GmailSendAsAlias)(nil)).Elem()
}

func (o GmailSendAsAliasOutput) ToGmailSendAsAliasOutput() GmailSendAsAliasOutput {
	return o
}

func (o GmailSendAsAliasOutput) ToGmailSendAsAliasOutputWithContext(ctx context.Context) GmailSendAsAliasOutput {
	return o
}

// A name that appears in the 'From:' header for mail sent using this alias. For custom 'from' addresses, when this is empty, Gmail will populate the 'From:' header with the name that is used for the primary address associated with the account. If the admin has disabled the ability for users to update their name format, requests to update this field for the primary login will silently fail.
func (o GmailSendAsAliasOutput) DisplayName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GmailSendAsAlias) pulumi.StringPtrOutput { return v.DisplayName }).(pulumi.StringPtrOutput)
}

// Whether this address is selected as the default 'From:' address in situations such as composing a new message or sending
// a vacation auto-reply. Every Gmail account has exactly one default send-as address, so the only legal value that clients
// may write to this field is true. Changing this from false to true for an address will result in this field becoming
// false for the other previous default address. Toggling an existing alias' default to false is not possible, another
// alias must be added/imported and toggled to true to remove the default from an existing alias. To avoid drift with
// Terraform, please change the previous default's config to false AFTER a new default is applied and perform a refresh to
// synchronize with remote state.
func (o GmailSendAsAliasOutput) IsDefault() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *GmailSendAsAlias) pulumi.BoolPtrOutput { return v.IsDefault }).(pulumi.BoolPtrOutput)
}

// Whether this address is the primary address used to login to the account. Every Gmail account has exactly one primary address, and it cannot be deleted from the collection of send-as aliases.
func (o GmailSendAsAliasOutput) IsPrimary() pulumi.BoolOutput {
	return o.ApplyT(func(v *GmailSendAsAlias) pulumi.BoolOutput { return v.IsPrimary }).(pulumi.BoolOutput)
}

// User's primary email address.
func (o GmailSendAsAliasOutput) PrimaryEmail() pulumi.StringOutput {
	return o.ApplyT(func(v *GmailSendAsAlias) pulumi.StringOutput { return v.PrimaryEmail }).(pulumi.StringOutput)
}

// An optional email address that is included in a 'Reply-To:' header for mail sent using this alias. If this is empty, Gmail will not generate a 'Reply-To:' header.
func (o GmailSendAsAliasOutput) ReplyToAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GmailSendAsAlias) pulumi.StringPtrOutput { return v.ReplyToAddress }).(pulumi.StringPtrOutput)
}

// The email address that appears in the 'From:' header for mail sent using this alias.
func (o GmailSendAsAliasOutput) SendAsEmail() pulumi.StringOutput {
	return o.ApplyT(func(v *GmailSendAsAlias) pulumi.StringOutput { return v.SendAsEmail }).(pulumi.StringOutput)
}

// An optional HTML signature that is included in messages composed with this alias in the Gmail web UI. This signature is added to new emails only.
func (o GmailSendAsAliasOutput) Signature() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GmailSendAsAlias) pulumi.StringPtrOutput { return v.Signature }).(pulumi.StringPtrOutput)
}

// An optional SMTP service that will be used as an outbound relay for mail sent using this alias. If this is empty, outbound mail will be sent directly from Gmail's servers to the destination SMTP service. This setting only applies to custom 'from' aliases.
func (o GmailSendAsAliasOutput) SmtpMsa() GmailSendAsAliasSmtpMsaPtrOutput {
	return o.ApplyT(func(v *GmailSendAsAlias) GmailSendAsAliasSmtpMsaPtrOutput { return v.SmtpMsa }).(GmailSendAsAliasSmtpMsaPtrOutput)
}

// Defaults to `true`. Whether Gmail should treat this address as an alias for the user's primary email address. This setting only applies to custom 'from' aliases. See https://support.google.com/a/answer/1710338 for help on making this decision
func (o GmailSendAsAliasOutput) TreatAsAlias() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *GmailSendAsAlias) pulumi.BoolPtrOutput { return v.TreatAsAlias }).(pulumi.BoolPtrOutput)
}

// Indicates whether this address has been verified for use as a send-as alias.
func (o GmailSendAsAliasOutput) VerificationStatus() pulumi.StringOutput {
	return o.ApplyT(func(v *GmailSendAsAlias) pulumi.StringOutput { return v.VerificationStatus }).(pulumi.StringOutput)
}

type GmailSendAsAliasArrayOutput struct{ *pulumi.OutputState }

func (GmailSendAsAliasArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GmailSendAsAlias)(nil)).Elem()
}

func (o GmailSendAsAliasArrayOutput) ToGmailSendAsAliasArrayOutput() GmailSendAsAliasArrayOutput {
	return o
}

func (o GmailSendAsAliasArrayOutput) ToGmailSendAsAliasArrayOutputWithContext(ctx context.Context) GmailSendAsAliasArrayOutput {
	return o
}

func (o GmailSendAsAliasArrayOutput) Index(i pulumi.IntInput) GmailSendAsAliasOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GmailSendAsAlias {
		return vs[0].([]*GmailSendAsAlias)[vs[1].(int)]
	}).(GmailSendAsAliasOutput)
}

type GmailSendAsAliasMapOutput struct{ *pulumi.OutputState }

func (GmailSendAsAliasMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GmailSendAsAlias)(nil)).Elem()
}

func (o GmailSendAsAliasMapOutput) ToGmailSendAsAliasMapOutput() GmailSendAsAliasMapOutput {
	return o
}

func (o GmailSendAsAliasMapOutput) ToGmailSendAsAliasMapOutputWithContext(ctx context.Context) GmailSendAsAliasMapOutput {
	return o
}

func (o GmailSendAsAliasMapOutput) MapIndex(k pulumi.StringInput) GmailSendAsAliasOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GmailSendAsAlias {
		return vs[0].(map[string]*GmailSendAsAlias)[vs[1].(string)]
	}).(GmailSendAsAliasOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GmailSendAsAliasInput)(nil)).Elem(), &GmailSendAsAlias{})
	pulumi.RegisterInputType(reflect.TypeOf((*GmailSendAsAliasArrayInput)(nil)).Elem(), GmailSendAsAliasArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GmailSendAsAliasMapInput)(nil)).Elem(), GmailSendAsAliasMap{})
	pulumi.RegisterOutputType(GmailSendAsAliasOutput{})
	pulumi.RegisterOutputType(GmailSendAsAliasArrayOutput{})
	pulumi.RegisterOutputType(GmailSendAsAliasMapOutput{})
}
