// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package googleworkspace

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// User resource manages Google Workspace Users. User resides under the `https://www.googleapis.com/auth/admin.directory.user` client scope.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"encoding/json"
//
// 	"github.com/pulumi/pulumi-googleworkspace/sdk/go/googleworkspace"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		birthday, err := googleworkspace.NewSchema(ctx, "birthday", &googleworkspace.SchemaArgs{
// 			SchemaName: pulumi.String("birthday"),
// 			Fields: SchemaFieldArray{
// 				&SchemaFieldArgs{
// 					FieldName: pulumi.String("birthday"),
// 					FieldType: pulumi.String("DATE"),
// 				},
// 				&SchemaFieldArgs{
// 					FieldName:   pulumi.String("favorite-numbers"),
// 					FieldType:   pulumi.String("INT64"),
// 					MultiValued: pulumi.Bool(true),
// 					NumericIndexingSpec: &SchemaFieldNumericIndexingSpecArgs{
// 						MinValue: pulumi.Float64(1),
// 						MaxValue: pulumi.Float64(100),
// 					},
// 				},
// 			},
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		tmpJSON0, err := json.Marshal("1970-01-20")
// 		if err != nil {
// 			return err
// 		}
// 		json0 := string(tmpJSON0)
// 		tmpJSON1, err := json.Marshal([]float64{
// 			1,
// 			2,
// 			3,
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		json1 := string(tmpJSON1)
// 		_, err = googleworkspace.NewUser(ctx, "dwight", &googleworkspace.UserArgs{
// 			PrimaryEmail: pulumi.String("dwight.schrute@example.com"),
// 			Password:     pulumi.String("34819d7beeabb9260a5c854bc85b3e44"),
// 			HashFunction: pulumi.String("MD5"),
// 			Name: &UserNameArgs{
// 				FamilyName: pulumi.String("Schrute"),
// 				GivenName:  pulumi.String("Dwight"),
// 			},
// 			Aliases: pulumi.StringArray{
// 				pulumi.String("assistant_to_regional_manager@example.com"),
// 			},
// 			Emails: UserEmailArray{
// 				&UserEmailArgs{
// 					Address: pulumi.String("dwight.schrute.dunder.mifflin@example.com"),
// 					Type:    pulumi.String("work"),
// 				},
// 			},
// 			Relations: UserRelationArray{
// 				&UserRelationArgs{
// 					Type:  pulumi.String("assistant"),
// 					Value: pulumi.String("Michael Scott"),
// 				},
// 			},
// 			Addresses: UserAddressArray{
// 				&UserAddressArgs{
// 					Country:       pulumi.String("USA"),
// 					CountryCode:   pulumi.String("US"),
// 					Locality:      pulumi.String("Scranton"),
// 					PoBox:         pulumi.String("123"),
// 					PostalCode:    pulumi.String("18508"),
// 					Region:        pulumi.String("PA"),
// 					StreetAddress: pulumi.String("123 Dunder Mifflin Pkwy"),
// 					Type:          pulumi.String("work"),
// 				},
// 			},
// 			Organizations: UserOrganizationArray{
// 				&UserOrganizationArgs{
// 					Department: pulumi.String("sales"),
// 					Location:   pulumi.String("Scranton"),
// 					Name:       pulumi.String("Dunder Mifflin"),
// 					Primary:    pulumi.Bool(true),
// 					Symbol:     pulumi.String("DUMI"),
// 					Title:      pulumi.String("member"),
// 					Type:       pulumi.String("work"),
// 				},
// 			},
// 			Phones: UserPhoneArray{
// 				&UserPhoneArgs{
// 					Type:  pulumi.String("home"),
// 					Value: pulumi.String("555-123-7890"),
// 				},
// 				&UserPhoneArgs{
// 					Type:    pulumi.String("work"),
// 					Primary: pulumi.Bool(true),
// 					Value:   pulumi.String("555-123-0987"),
// 				},
// 			},
// 			Keywords: UserKeywordArray{
// 				&UserKeywordArgs{
// 					Type:  pulumi.String("occupation"),
// 					Value: pulumi.String("salesperson"),
// 				},
// 			},
// 			CustomSchemas: UserCustomSchemaArray{
// 				&UserCustomSchemaArgs{
// 					SchemaName: birthday.SchemaName,
// 					SchemaValues: pulumi.StringMap{
// 						"birthday":         pulumi.String(json0),
// 						"favorite-numbers": pulumi.String(json1),
// 					},
// 				},
// 			},
// 			RecoveryEmail: pulumi.String("dwightkschrute@example.com"),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// ## Import
//
// ```sh
//  $ pulumi import googleworkspace:index/user:User dwight 123456789012345678901
// ```
//
// # or with email as id
//
// ```sh
//  $ pulumi import googleworkspace:index/user:User dwight dwight.schrute@example.com
// ```
type User struct {
	pulumi.CustomResourceState

	// A list of the user's addresses. The maximum allowed data size is 10Kb.
	Addresses UserAddressArrayOutput `pulumi:"addresses"`
	// This property is true if the user has completed an initial login and accepted the Terms of Service agreement.
	AgreedToTerms pulumi.BoolOutput `pulumi:"agreedToTerms"`
	// asps.list of the user's alias email addresses.
	Aliases pulumi.StringArrayOutput `pulumi:"aliases"`
	// Indicates if user is archived.
	Archived pulumi.BoolPtrOutput `pulumi:"archived"`
	// Indicates if the user is forced to change their password at next login. This setting doesn't apply when the user signs
	// in via a third-party identity provider.
	ChangePasswordAtNextLogin pulumi.BoolPtrOutput `pulumi:"changePasswordAtNextLogin"`
	// The time the user's account was created. The value is in ISO 8601 date and time format. The time is the complete date
	// plus hours, minutes, and seconds in the form YYYY-MM-DDThh:mm:ssTZD. For example, 2010-04-05T17:30:04+01:00.
	CreationTime pulumi.StringOutput `pulumi:"creationTime"`
	// Custom fields of the user.
	CustomSchemas UserCustomSchemaArrayOutput `pulumi:"customSchemas"`
	// The customer ID to retrieve all account users. You can use the alias my_customer to represent your account's customerId.
	// As a reseller administrator, you can use the resold customer account's customerId. To get a customerId, use the
	// account's primary domain in the domain parameter of a users.list request.
	CustomerId pulumi.StringOutput `pulumi:"customerId"`
	// The time the user's account was deleted. The value is in ISO 8601 date and time format The time is the complete date
	// plus hours, minutes, and seconds in the form YYYY-MM-DDThh:mm:ssTZD. For example 2010-04-05T17:30:04+01:00.
	DeletionTime pulumi.StringOutput `pulumi:"deletionTime"`
	// A list of the user's email addresses. The maximum allowed data size is 10Kb.
	Emails UserEmailArrayOutput `pulumi:"emails"`
	// ETag of the resource.
	Etag pulumi.StringOutput `pulumi:"etag"`
	// A list of external IDs for the user, such as an employee or network ID. The maximum allowed data size is 2Kb.
	ExternalIds UserExternalIdArrayOutput `pulumi:"externalIds"`
	// Stores the hash format of the password property. We recommend sending the password property value as a base 16 bit
	// hexadecimal-encoded hash value. Set the hashFunction values as either the SHA-1, MD5, or crypt hash format.
	HashFunction pulumi.StringPtrOutput `pulumi:"hashFunction"`
	// The user's Instant Messenger (IM) accounts. A user account can have multiple ims properties. But, only one of these ims
	// properties can be the primary IM contact. The maximum allowed data size is 2Kb.
	Ims UserImArrayOutput `pulumi:"ims"`
	// Indicates if the user's profile is visible in the Google Workspace global address list when the contact sharing feature
	// is enabled for the domain.
	IncludeInGlobalAddressList pulumi.BoolPtrOutput `pulumi:"includeInGlobalAddressList"`
	// If true, the user's IP address is added to the allow list.
	IpAllowlist pulumi.BoolPtrOutput `pulumi:"ipAllowlist"`
	// Indicates a user with super admininistrator privileges.
	IsAdmin pulumi.BoolOutput `pulumi:"isAdmin"`
	// Indicates if the user is a delegated administrator.
	IsDelegatedAdmin pulumi.BoolOutput `pulumi:"isDelegatedAdmin"`
	// Is 2-step verification enforced.
	IsEnforcedIn2StepVerification pulumi.BoolOutput `pulumi:"isEnforcedIn2StepVerification"`
	// Is enrolled in 2-step verification.
	IsEnrolledIn2StepVerification pulumi.BoolOutput `pulumi:"isEnrolledIn2StepVerification"`
	// Indicates if the user's Google mailbox is created. This property is only applicable if the user has been assigned a
	// Gmail license.
	IsMailboxSetup pulumi.BoolOutput `pulumi:"isMailboxSetup"`
	// A list of the user's keywords. The maximum allowed data size is 1Kb.
	Keywords UserKeywordArrayOutput `pulumi:"keywords"`
	// A list of the user's languages. The maximum allowed data size is 1Kb.
	Languages UserLanguageArrayOutput `pulumi:"languages"`
	// The last time the user logged into the user's account. The value is in ISO 8601 date and time format. The time is the
	// complete date plus hours, minutes, and seconds in the form YYYY-MM-DDThh:mm:ssTZD. For example,
	// 2010-04-05T17:30:04+01:00.
	LastLoginTime pulumi.StringOutput `pulumi:"lastLoginTime"`
	// A list of the user's locations. The maximum allowed data size is 10Kb.
	Locations UserLocationArrayOutput `pulumi:"locations"`
	// Holds the given and family names of the user, and the read-only fullName value. The maximum number of characters in the
	// givenName and in the familyName values is 60. In addition, name values support unicode/UTF-8 characters, and can contain
	// spaces, letters (a-z), numbers (0-9), dashes (-), forward slashes (/), and periods (.). Maximum allowed data size for
	// this field is 1Kb.
	Name UserNameOutput `pulumi:"name"`
	// asps.list of the user's non-editable alias email addresses. These are typically outside the account's primary domain or
	// sub-domain.
	NonEditableAliases pulumi.StringArrayOutput `pulumi:"nonEditableAliases"`
	// The full path of the parent organization associated with the user. If the parent organization is the top-level, it is
	// represented as a forward slash (/).
	OrgUnitPath pulumi.StringOutput `pulumi:"orgUnitPath"`
	// A list of organizations the user belongs to. The maximum allowed data size is 10Kb.
	Organizations UserOrganizationArrayOutput `pulumi:"organizations"`
	// Stores the password for the user account. A password can contain any combination of ASCII characters. A minimum of 8
	// characters is required. The maximum length is 100 characters. As the API does not return the value of password, this
	// field is write-only, and the value stored in the state will be what is provided in the configuration. The field is
	// required on create and will be empty on import.
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// A list of the user's phone numbers. The maximum allowed data size is 1Kb.
	Phones UserPhoneArrayOutput `pulumi:"phones"`
	// A list of POSIX account information for the user.
	PosixAccounts UserPosixAccountArrayOutput `pulumi:"posixAccounts"`
	// The user's primary email address. The primaryEmail must be unique and cannot be an alias of another user.
	PrimaryEmail pulumi.StringOutput `pulumi:"primaryEmail"`
	// Recovery email of the user.
	RecoveryEmail pulumi.StringPtrOutput `pulumi:"recoveryEmail"`
	// Recovery phone of the user. The phone number must be in the E.164 format, starting with the plus sign (+). Example:
	// +16506661212.
	RecoveryPhone pulumi.StringPtrOutput `pulumi:"recoveryPhone"`
	// A list of the user's relationships to other users. The maximum allowed data size for this field is 2Kb.
	Relations UserRelationArrayOutput `pulumi:"relations"`
	// A list of SSH public keys. The maximum allowed data size is 10Kb.
	SshPublicKeys UserSshPublicKeyArrayOutput `pulumi:"sshPublicKeys"`
	// Indicates if user is suspended.
	Suspended pulumi.BoolPtrOutput `pulumi:"suspended"`
	// Has the reason a user account is suspended either by the administrator or by Google at the time of suspension. The
	// property is returned only if the suspended property is true.
	SuspensionReason pulumi.StringOutput `pulumi:"suspensionReason"`
	// ETag of the user's photo
	ThumbnailPhotoEtag pulumi.StringOutput `pulumi:"thumbnailPhotoEtag"`
	// Photo Url of the user.
	ThumbnailPhotoUrl pulumi.StringOutput `pulumi:"thumbnailPhotoUrl"`
	// A list of the user's websites. The maximum allowed data size is 2Kb.
	Websites UserWebsiteArrayOutput `pulumi:"websites"`
}

// NewUser registers a new resource with the given unique name, arguments, and options.
func NewUser(ctx *pulumi.Context,
	name string, args *UserArgs, opts ...pulumi.ResourceOption) (*User, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PrimaryEmail == nil {
		return nil, errors.New("invalid value for required argument 'PrimaryEmail'")
	}
	var resource User
	err := ctx.RegisterResource("googleworkspace:index/user:User", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUser gets an existing User resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUser(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserState, opts ...pulumi.ResourceOption) (*User, error) {
	var resource User
	err := ctx.ReadResource("googleworkspace:index/user:User", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering User resources.
type userState struct {
	// A list of the user's addresses. The maximum allowed data size is 10Kb.
	Addresses []UserAddress `pulumi:"addresses"`
	// This property is true if the user has completed an initial login and accepted the Terms of Service agreement.
	AgreedToTerms *bool `pulumi:"agreedToTerms"`
	// asps.list of the user's alias email addresses.
	Aliases []string `pulumi:"aliases"`
	// Indicates if user is archived.
	Archived *bool `pulumi:"archived"`
	// Indicates if the user is forced to change their password at next login. This setting doesn't apply when the user signs
	// in via a third-party identity provider.
	ChangePasswordAtNextLogin *bool `pulumi:"changePasswordAtNextLogin"`
	// The time the user's account was created. The value is in ISO 8601 date and time format. The time is the complete date
	// plus hours, minutes, and seconds in the form YYYY-MM-DDThh:mm:ssTZD. For example, 2010-04-05T17:30:04+01:00.
	CreationTime *string `pulumi:"creationTime"`
	// Custom fields of the user.
	CustomSchemas []UserCustomSchema `pulumi:"customSchemas"`
	// The customer ID to retrieve all account users. You can use the alias my_customer to represent your account's customerId.
	// As a reseller administrator, you can use the resold customer account's customerId. To get a customerId, use the
	// account's primary domain in the domain parameter of a users.list request.
	CustomerId *string `pulumi:"customerId"`
	// The time the user's account was deleted. The value is in ISO 8601 date and time format The time is the complete date
	// plus hours, minutes, and seconds in the form YYYY-MM-DDThh:mm:ssTZD. For example 2010-04-05T17:30:04+01:00.
	DeletionTime *string `pulumi:"deletionTime"`
	// A list of the user's email addresses. The maximum allowed data size is 10Kb.
	Emails []UserEmail `pulumi:"emails"`
	// ETag of the resource.
	Etag *string `pulumi:"etag"`
	// A list of external IDs for the user, such as an employee or network ID. The maximum allowed data size is 2Kb.
	ExternalIds []UserExternalId `pulumi:"externalIds"`
	// Stores the hash format of the password property. We recommend sending the password property value as a base 16 bit
	// hexadecimal-encoded hash value. Set the hashFunction values as either the SHA-1, MD5, or crypt hash format.
	HashFunction *string `pulumi:"hashFunction"`
	// The user's Instant Messenger (IM) accounts. A user account can have multiple ims properties. But, only one of these ims
	// properties can be the primary IM contact. The maximum allowed data size is 2Kb.
	Ims []UserIm `pulumi:"ims"`
	// Indicates if the user's profile is visible in the Google Workspace global address list when the contact sharing feature
	// is enabled for the domain.
	IncludeInGlobalAddressList *bool `pulumi:"includeInGlobalAddressList"`
	// If true, the user's IP address is added to the allow list.
	IpAllowlist *bool `pulumi:"ipAllowlist"`
	// Indicates a user with super admininistrator privileges.
	IsAdmin *bool `pulumi:"isAdmin"`
	// Indicates if the user is a delegated administrator.
	IsDelegatedAdmin *bool `pulumi:"isDelegatedAdmin"`
	// Is 2-step verification enforced.
	IsEnforcedIn2StepVerification *bool `pulumi:"isEnforcedIn2StepVerification"`
	// Is enrolled in 2-step verification.
	IsEnrolledIn2StepVerification *bool `pulumi:"isEnrolledIn2StepVerification"`
	// Indicates if the user's Google mailbox is created. This property is only applicable if the user has been assigned a
	// Gmail license.
	IsMailboxSetup *bool `pulumi:"isMailboxSetup"`
	// A list of the user's keywords. The maximum allowed data size is 1Kb.
	Keywords []UserKeyword `pulumi:"keywords"`
	// A list of the user's languages. The maximum allowed data size is 1Kb.
	Languages []UserLanguage `pulumi:"languages"`
	// The last time the user logged into the user's account. The value is in ISO 8601 date and time format. The time is the
	// complete date plus hours, minutes, and seconds in the form YYYY-MM-DDThh:mm:ssTZD. For example,
	// 2010-04-05T17:30:04+01:00.
	LastLoginTime *string `pulumi:"lastLoginTime"`
	// A list of the user's locations. The maximum allowed data size is 10Kb.
	Locations []UserLocation `pulumi:"locations"`
	// Holds the given and family names of the user, and the read-only fullName value. The maximum number of characters in the
	// givenName and in the familyName values is 60. In addition, name values support unicode/UTF-8 characters, and can contain
	// spaces, letters (a-z), numbers (0-9), dashes (-), forward slashes (/), and periods (.). Maximum allowed data size for
	// this field is 1Kb.
	Name *UserName `pulumi:"name"`
	// asps.list of the user's non-editable alias email addresses. These are typically outside the account's primary domain or
	// sub-domain.
	NonEditableAliases []string `pulumi:"nonEditableAliases"`
	// The full path of the parent organization associated with the user. If the parent organization is the top-level, it is
	// represented as a forward slash (/).
	OrgUnitPath *string `pulumi:"orgUnitPath"`
	// A list of organizations the user belongs to. The maximum allowed data size is 10Kb.
	Organizations []UserOrganization `pulumi:"organizations"`
	// Stores the password for the user account. A password can contain any combination of ASCII characters. A minimum of 8
	// characters is required. The maximum length is 100 characters. As the API does not return the value of password, this
	// field is write-only, and the value stored in the state will be what is provided in the configuration. The field is
	// required on create and will be empty on import.
	Password *string `pulumi:"password"`
	// A list of the user's phone numbers. The maximum allowed data size is 1Kb.
	Phones []UserPhone `pulumi:"phones"`
	// A list of POSIX account information for the user.
	PosixAccounts []UserPosixAccount `pulumi:"posixAccounts"`
	// The user's primary email address. The primaryEmail must be unique and cannot be an alias of another user.
	PrimaryEmail *string `pulumi:"primaryEmail"`
	// Recovery email of the user.
	RecoveryEmail *string `pulumi:"recoveryEmail"`
	// Recovery phone of the user. The phone number must be in the E.164 format, starting with the plus sign (+). Example:
	// +16506661212.
	RecoveryPhone *string `pulumi:"recoveryPhone"`
	// A list of the user's relationships to other users. The maximum allowed data size for this field is 2Kb.
	Relations []UserRelation `pulumi:"relations"`
	// A list of SSH public keys. The maximum allowed data size is 10Kb.
	SshPublicKeys []UserSshPublicKey `pulumi:"sshPublicKeys"`
	// Indicates if user is suspended.
	Suspended *bool `pulumi:"suspended"`
	// Has the reason a user account is suspended either by the administrator or by Google at the time of suspension. The
	// property is returned only if the suspended property is true.
	SuspensionReason *string `pulumi:"suspensionReason"`
	// ETag of the user's photo
	ThumbnailPhotoEtag *string `pulumi:"thumbnailPhotoEtag"`
	// Photo Url of the user.
	ThumbnailPhotoUrl *string `pulumi:"thumbnailPhotoUrl"`
	// A list of the user's websites. The maximum allowed data size is 2Kb.
	Websites []UserWebsite `pulumi:"websites"`
}

type UserState struct {
	// A list of the user's addresses. The maximum allowed data size is 10Kb.
	Addresses UserAddressArrayInput
	// This property is true if the user has completed an initial login and accepted the Terms of Service agreement.
	AgreedToTerms pulumi.BoolPtrInput
	// asps.list of the user's alias email addresses.
	Aliases pulumi.StringArrayInput
	// Indicates if user is archived.
	Archived pulumi.BoolPtrInput
	// Indicates if the user is forced to change their password at next login. This setting doesn't apply when the user signs
	// in via a third-party identity provider.
	ChangePasswordAtNextLogin pulumi.BoolPtrInput
	// The time the user's account was created. The value is in ISO 8601 date and time format. The time is the complete date
	// plus hours, minutes, and seconds in the form YYYY-MM-DDThh:mm:ssTZD. For example, 2010-04-05T17:30:04+01:00.
	CreationTime pulumi.StringPtrInput
	// Custom fields of the user.
	CustomSchemas UserCustomSchemaArrayInput
	// The customer ID to retrieve all account users. You can use the alias my_customer to represent your account's customerId.
	// As a reseller administrator, you can use the resold customer account's customerId. To get a customerId, use the
	// account's primary domain in the domain parameter of a users.list request.
	CustomerId pulumi.StringPtrInput
	// The time the user's account was deleted. The value is in ISO 8601 date and time format The time is the complete date
	// plus hours, minutes, and seconds in the form YYYY-MM-DDThh:mm:ssTZD. For example 2010-04-05T17:30:04+01:00.
	DeletionTime pulumi.StringPtrInput
	// A list of the user's email addresses. The maximum allowed data size is 10Kb.
	Emails UserEmailArrayInput
	// ETag of the resource.
	Etag pulumi.StringPtrInput
	// A list of external IDs for the user, such as an employee or network ID. The maximum allowed data size is 2Kb.
	ExternalIds UserExternalIdArrayInput
	// Stores the hash format of the password property. We recommend sending the password property value as a base 16 bit
	// hexadecimal-encoded hash value. Set the hashFunction values as either the SHA-1, MD5, or crypt hash format.
	HashFunction pulumi.StringPtrInput
	// The user's Instant Messenger (IM) accounts. A user account can have multiple ims properties. But, only one of these ims
	// properties can be the primary IM contact. The maximum allowed data size is 2Kb.
	Ims UserImArrayInput
	// Indicates if the user's profile is visible in the Google Workspace global address list when the contact sharing feature
	// is enabled for the domain.
	IncludeInGlobalAddressList pulumi.BoolPtrInput
	// If true, the user's IP address is added to the allow list.
	IpAllowlist pulumi.BoolPtrInput
	// Indicates a user with super admininistrator privileges.
	IsAdmin pulumi.BoolPtrInput
	// Indicates if the user is a delegated administrator.
	IsDelegatedAdmin pulumi.BoolPtrInput
	// Is 2-step verification enforced.
	IsEnforcedIn2StepVerification pulumi.BoolPtrInput
	// Is enrolled in 2-step verification.
	IsEnrolledIn2StepVerification pulumi.BoolPtrInput
	// Indicates if the user's Google mailbox is created. This property is only applicable if the user has been assigned a
	// Gmail license.
	IsMailboxSetup pulumi.BoolPtrInput
	// A list of the user's keywords. The maximum allowed data size is 1Kb.
	Keywords UserKeywordArrayInput
	// A list of the user's languages. The maximum allowed data size is 1Kb.
	Languages UserLanguageArrayInput
	// The last time the user logged into the user's account. The value is in ISO 8601 date and time format. The time is the
	// complete date plus hours, minutes, and seconds in the form YYYY-MM-DDThh:mm:ssTZD. For example,
	// 2010-04-05T17:30:04+01:00.
	LastLoginTime pulumi.StringPtrInput
	// A list of the user's locations. The maximum allowed data size is 10Kb.
	Locations UserLocationArrayInput
	// Holds the given and family names of the user, and the read-only fullName value. The maximum number of characters in the
	// givenName and in the familyName values is 60. In addition, name values support unicode/UTF-8 characters, and can contain
	// spaces, letters (a-z), numbers (0-9), dashes (-), forward slashes (/), and periods (.). Maximum allowed data size for
	// this field is 1Kb.
	Name UserNamePtrInput
	// asps.list of the user's non-editable alias email addresses. These are typically outside the account's primary domain or
	// sub-domain.
	NonEditableAliases pulumi.StringArrayInput
	// The full path of the parent organization associated with the user. If the parent organization is the top-level, it is
	// represented as a forward slash (/).
	OrgUnitPath pulumi.StringPtrInput
	// A list of organizations the user belongs to. The maximum allowed data size is 10Kb.
	Organizations UserOrganizationArrayInput
	// Stores the password for the user account. A password can contain any combination of ASCII characters. A minimum of 8
	// characters is required. The maximum length is 100 characters. As the API does not return the value of password, this
	// field is write-only, and the value stored in the state will be what is provided in the configuration. The field is
	// required on create and will be empty on import.
	Password pulumi.StringPtrInput
	// A list of the user's phone numbers. The maximum allowed data size is 1Kb.
	Phones UserPhoneArrayInput
	// A list of POSIX account information for the user.
	PosixAccounts UserPosixAccountArrayInput
	// The user's primary email address. The primaryEmail must be unique and cannot be an alias of another user.
	PrimaryEmail pulumi.StringPtrInput
	// Recovery email of the user.
	RecoveryEmail pulumi.StringPtrInput
	// Recovery phone of the user. The phone number must be in the E.164 format, starting with the plus sign (+). Example:
	// +16506661212.
	RecoveryPhone pulumi.StringPtrInput
	// A list of the user's relationships to other users. The maximum allowed data size for this field is 2Kb.
	Relations UserRelationArrayInput
	// A list of SSH public keys. The maximum allowed data size is 10Kb.
	SshPublicKeys UserSshPublicKeyArrayInput
	// Indicates if user is suspended.
	Suspended pulumi.BoolPtrInput
	// Has the reason a user account is suspended either by the administrator or by Google at the time of suspension. The
	// property is returned only if the suspended property is true.
	SuspensionReason pulumi.StringPtrInput
	// ETag of the user's photo
	ThumbnailPhotoEtag pulumi.StringPtrInput
	// Photo Url of the user.
	ThumbnailPhotoUrl pulumi.StringPtrInput
	// A list of the user's websites. The maximum allowed data size is 2Kb.
	Websites UserWebsiteArrayInput
}

func (UserState) ElementType() reflect.Type {
	return reflect.TypeOf((*userState)(nil)).Elem()
}

type userArgs struct {
	// A list of the user's addresses. The maximum allowed data size is 10Kb.
	Addresses []UserAddress `pulumi:"addresses"`
	// asps.list of the user's alias email addresses.
	Aliases []string `pulumi:"aliases"`
	// Indicates if user is archived.
	Archived *bool `pulumi:"archived"`
	// Indicates if the user is forced to change their password at next login. This setting doesn't apply when the user signs
	// in via a third-party identity provider.
	ChangePasswordAtNextLogin *bool `pulumi:"changePasswordAtNextLogin"`
	// Custom fields of the user.
	CustomSchemas []UserCustomSchema `pulumi:"customSchemas"`
	// A list of the user's email addresses. The maximum allowed data size is 10Kb.
	Emails []UserEmail `pulumi:"emails"`
	// A list of external IDs for the user, such as an employee or network ID. The maximum allowed data size is 2Kb.
	ExternalIds []UserExternalId `pulumi:"externalIds"`
	// Stores the hash format of the password property. We recommend sending the password property value as a base 16 bit
	// hexadecimal-encoded hash value. Set the hashFunction values as either the SHA-1, MD5, or crypt hash format.
	HashFunction *string `pulumi:"hashFunction"`
	// The user's Instant Messenger (IM) accounts. A user account can have multiple ims properties. But, only one of these ims
	// properties can be the primary IM contact. The maximum allowed data size is 2Kb.
	Ims []UserIm `pulumi:"ims"`
	// Indicates if the user's profile is visible in the Google Workspace global address list when the contact sharing feature
	// is enabled for the domain.
	IncludeInGlobalAddressList *bool `pulumi:"includeInGlobalAddressList"`
	// If true, the user's IP address is added to the allow list.
	IpAllowlist *bool `pulumi:"ipAllowlist"`
	// Indicates a user with super admininistrator privileges.
	IsAdmin *bool `pulumi:"isAdmin"`
	// A list of the user's keywords. The maximum allowed data size is 1Kb.
	Keywords []UserKeyword `pulumi:"keywords"`
	// A list of the user's languages. The maximum allowed data size is 1Kb.
	Languages []UserLanguage `pulumi:"languages"`
	// A list of the user's locations. The maximum allowed data size is 10Kb.
	Locations []UserLocation `pulumi:"locations"`
	// Holds the given and family names of the user, and the read-only fullName value. The maximum number of characters in the
	// givenName and in the familyName values is 60. In addition, name values support unicode/UTF-8 characters, and can contain
	// spaces, letters (a-z), numbers (0-9), dashes (-), forward slashes (/), and periods (.). Maximum allowed data size for
	// this field is 1Kb.
	Name *UserName `pulumi:"name"`
	// The full path of the parent organization associated with the user. If the parent organization is the top-level, it is
	// represented as a forward slash (/).
	OrgUnitPath *string `pulumi:"orgUnitPath"`
	// A list of organizations the user belongs to. The maximum allowed data size is 10Kb.
	Organizations []UserOrganization `pulumi:"organizations"`
	// Stores the password for the user account. A password can contain any combination of ASCII characters. A minimum of 8
	// characters is required. The maximum length is 100 characters. As the API does not return the value of password, this
	// field is write-only, and the value stored in the state will be what is provided in the configuration. The field is
	// required on create and will be empty on import.
	Password *string `pulumi:"password"`
	// A list of the user's phone numbers. The maximum allowed data size is 1Kb.
	Phones []UserPhone `pulumi:"phones"`
	// A list of POSIX account information for the user.
	PosixAccounts []UserPosixAccount `pulumi:"posixAccounts"`
	// The user's primary email address. The primaryEmail must be unique and cannot be an alias of another user.
	PrimaryEmail string `pulumi:"primaryEmail"`
	// Recovery email of the user.
	RecoveryEmail *string `pulumi:"recoveryEmail"`
	// Recovery phone of the user. The phone number must be in the E.164 format, starting with the plus sign (+). Example:
	// +16506661212.
	RecoveryPhone *string `pulumi:"recoveryPhone"`
	// A list of the user's relationships to other users. The maximum allowed data size for this field is 2Kb.
	Relations []UserRelation `pulumi:"relations"`
	// A list of SSH public keys. The maximum allowed data size is 10Kb.
	SshPublicKeys []UserSshPublicKey `pulumi:"sshPublicKeys"`
	// Indicates if user is suspended.
	Suspended *bool `pulumi:"suspended"`
	// A list of the user's websites. The maximum allowed data size is 2Kb.
	Websites []UserWebsite `pulumi:"websites"`
}

// The set of arguments for constructing a User resource.
type UserArgs struct {
	// A list of the user's addresses. The maximum allowed data size is 10Kb.
	Addresses UserAddressArrayInput
	// asps.list of the user's alias email addresses.
	Aliases pulumi.StringArrayInput
	// Indicates if user is archived.
	Archived pulumi.BoolPtrInput
	// Indicates if the user is forced to change their password at next login. This setting doesn't apply when the user signs
	// in via a third-party identity provider.
	ChangePasswordAtNextLogin pulumi.BoolPtrInput
	// Custom fields of the user.
	CustomSchemas UserCustomSchemaArrayInput
	// A list of the user's email addresses. The maximum allowed data size is 10Kb.
	Emails UserEmailArrayInput
	// A list of external IDs for the user, such as an employee or network ID. The maximum allowed data size is 2Kb.
	ExternalIds UserExternalIdArrayInput
	// Stores the hash format of the password property. We recommend sending the password property value as a base 16 bit
	// hexadecimal-encoded hash value. Set the hashFunction values as either the SHA-1, MD5, or crypt hash format.
	HashFunction pulumi.StringPtrInput
	// The user's Instant Messenger (IM) accounts. A user account can have multiple ims properties. But, only one of these ims
	// properties can be the primary IM contact. The maximum allowed data size is 2Kb.
	Ims UserImArrayInput
	// Indicates if the user's profile is visible in the Google Workspace global address list when the contact sharing feature
	// is enabled for the domain.
	IncludeInGlobalAddressList pulumi.BoolPtrInput
	// If true, the user's IP address is added to the allow list.
	IpAllowlist pulumi.BoolPtrInput
	// Indicates a user with super admininistrator privileges.
	IsAdmin pulumi.BoolPtrInput
	// A list of the user's keywords. The maximum allowed data size is 1Kb.
	Keywords UserKeywordArrayInput
	// A list of the user's languages. The maximum allowed data size is 1Kb.
	Languages UserLanguageArrayInput
	// A list of the user's locations. The maximum allowed data size is 10Kb.
	Locations UserLocationArrayInput
	// Holds the given and family names of the user, and the read-only fullName value. The maximum number of characters in the
	// givenName and in the familyName values is 60. In addition, name values support unicode/UTF-8 characters, and can contain
	// spaces, letters (a-z), numbers (0-9), dashes (-), forward slashes (/), and periods (.). Maximum allowed data size for
	// this field is 1Kb.
	Name UserNamePtrInput
	// The full path of the parent organization associated with the user. If the parent organization is the top-level, it is
	// represented as a forward slash (/).
	OrgUnitPath pulumi.StringPtrInput
	// A list of organizations the user belongs to. The maximum allowed data size is 10Kb.
	Organizations UserOrganizationArrayInput
	// Stores the password for the user account. A password can contain any combination of ASCII characters. A minimum of 8
	// characters is required. The maximum length is 100 characters. As the API does not return the value of password, this
	// field is write-only, and the value stored in the state will be what is provided in the configuration. The field is
	// required on create and will be empty on import.
	Password pulumi.StringPtrInput
	// A list of the user's phone numbers. The maximum allowed data size is 1Kb.
	Phones UserPhoneArrayInput
	// A list of POSIX account information for the user.
	PosixAccounts UserPosixAccountArrayInput
	// The user's primary email address. The primaryEmail must be unique and cannot be an alias of another user.
	PrimaryEmail pulumi.StringInput
	// Recovery email of the user.
	RecoveryEmail pulumi.StringPtrInput
	// Recovery phone of the user. The phone number must be in the E.164 format, starting with the plus sign (+). Example:
	// +16506661212.
	RecoveryPhone pulumi.StringPtrInput
	// A list of the user's relationships to other users. The maximum allowed data size for this field is 2Kb.
	Relations UserRelationArrayInput
	// A list of SSH public keys. The maximum allowed data size is 10Kb.
	SshPublicKeys UserSshPublicKeyArrayInput
	// Indicates if user is suspended.
	Suspended pulumi.BoolPtrInput
	// A list of the user's websites. The maximum allowed data size is 2Kb.
	Websites UserWebsiteArrayInput
}

func (UserArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userArgs)(nil)).Elem()
}

type UserInput interface {
	pulumi.Input

	ToUserOutput() UserOutput
	ToUserOutputWithContext(ctx context.Context) UserOutput
}

func (*User) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (i *User) ToUserOutput() UserOutput {
	return i.ToUserOutputWithContext(context.Background())
}

func (i *User) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserOutput)
}

// UserArrayInput is an input type that accepts UserArray and UserArrayOutput values.
// You can construct a concrete instance of `UserArrayInput` via:
//
//          UserArray{ UserArgs{...} }
type UserArrayInput interface {
	pulumi.Input

	ToUserArrayOutput() UserArrayOutput
	ToUserArrayOutputWithContext(context.Context) UserArrayOutput
}

type UserArray []UserInput

func (UserArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*User)(nil)).Elem()
}

func (i UserArray) ToUserArrayOutput() UserArrayOutput {
	return i.ToUserArrayOutputWithContext(context.Background())
}

func (i UserArray) ToUserArrayOutputWithContext(ctx context.Context) UserArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserArrayOutput)
}

// UserMapInput is an input type that accepts UserMap and UserMapOutput values.
// You can construct a concrete instance of `UserMapInput` via:
//
//          UserMap{ "key": UserArgs{...} }
type UserMapInput interface {
	pulumi.Input

	ToUserMapOutput() UserMapOutput
	ToUserMapOutputWithContext(context.Context) UserMapOutput
}

type UserMap map[string]UserInput

func (UserMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*User)(nil)).Elem()
}

func (i UserMap) ToUserMapOutput() UserMapOutput {
	return i.ToUserMapOutputWithContext(context.Background())
}

func (i UserMap) ToUserMapOutputWithContext(ctx context.Context) UserMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserMapOutput)
}

type UserOutput struct{ *pulumi.OutputState }

func (UserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (o UserOutput) ToUserOutput() UserOutput {
	return o
}

func (o UserOutput) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return o
}

// A list of the user's addresses. The maximum allowed data size is 10Kb.
func (o UserOutput) Addresses() UserAddressArrayOutput {
	return o.ApplyT(func(v *User) UserAddressArrayOutput { return v.Addresses }).(UserAddressArrayOutput)
}

// This property is true if the user has completed an initial login and accepted the Terms of Service agreement.
func (o UserOutput) AgreedToTerms() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.AgreedToTerms }).(pulumi.BoolOutput)
}

// asps.list of the user's alias email addresses.
func (o UserOutput) Aliases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *User) pulumi.StringArrayOutput { return v.Aliases }).(pulumi.StringArrayOutput)
}

// Indicates if user is archived.
func (o UserOutput) Archived() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *User) pulumi.BoolPtrOutput { return v.Archived }).(pulumi.BoolPtrOutput)
}

// Indicates if the user is forced to change their password at next login. This setting doesn't apply when the user signs
// in via a third-party identity provider.
func (o UserOutput) ChangePasswordAtNextLogin() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *User) pulumi.BoolPtrOutput { return v.ChangePasswordAtNextLogin }).(pulumi.BoolPtrOutput)
}

// The time the user's account was created. The value is in ISO 8601 date and time format. The time is the complete date
// plus hours, minutes, and seconds in the form YYYY-MM-DDThh:mm:ssTZD. For example, 2010-04-05T17:30:04+01:00.
func (o UserOutput) CreationTime() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.CreationTime }).(pulumi.StringOutput)
}

// Custom fields of the user.
func (o UserOutput) CustomSchemas() UserCustomSchemaArrayOutput {
	return o.ApplyT(func(v *User) UserCustomSchemaArrayOutput { return v.CustomSchemas }).(UserCustomSchemaArrayOutput)
}

// The customer ID to retrieve all account users. You can use the alias my_customer to represent your account's customerId.
// As a reseller administrator, you can use the resold customer account's customerId. To get a customerId, use the
// account's primary domain in the domain parameter of a users.list request.
func (o UserOutput) CustomerId() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.CustomerId }).(pulumi.StringOutput)
}

// The time the user's account was deleted. The value is in ISO 8601 date and time format The time is the complete date
// plus hours, minutes, and seconds in the form YYYY-MM-DDThh:mm:ssTZD. For example 2010-04-05T17:30:04+01:00.
func (o UserOutput) DeletionTime() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.DeletionTime }).(pulumi.StringOutput)
}

// A list of the user's email addresses. The maximum allowed data size is 10Kb.
func (o UserOutput) Emails() UserEmailArrayOutput {
	return o.ApplyT(func(v *User) UserEmailArrayOutput { return v.Emails }).(UserEmailArrayOutput)
}

// ETag of the resource.
func (o UserOutput) Etag() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Etag }).(pulumi.StringOutput)
}

// A list of external IDs for the user, such as an employee or network ID. The maximum allowed data size is 2Kb.
func (o UserOutput) ExternalIds() UserExternalIdArrayOutput {
	return o.ApplyT(func(v *User) UserExternalIdArrayOutput { return v.ExternalIds }).(UserExternalIdArrayOutput)
}

// Stores the hash format of the password property. We recommend sending the password property value as a base 16 bit
// hexadecimal-encoded hash value. Set the hashFunction values as either the SHA-1, MD5, or crypt hash format.
func (o UserOutput) HashFunction() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.HashFunction }).(pulumi.StringPtrOutput)
}

// The user's Instant Messenger (IM) accounts. A user account can have multiple ims properties. But, only one of these ims
// properties can be the primary IM contact. The maximum allowed data size is 2Kb.
func (o UserOutput) Ims() UserImArrayOutput {
	return o.ApplyT(func(v *User) UserImArrayOutput { return v.Ims }).(UserImArrayOutput)
}

// Indicates if the user's profile is visible in the Google Workspace global address list when the contact sharing feature
// is enabled for the domain.
func (o UserOutput) IncludeInGlobalAddressList() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *User) pulumi.BoolPtrOutput { return v.IncludeInGlobalAddressList }).(pulumi.BoolPtrOutput)
}

// If true, the user's IP address is added to the allow list.
func (o UserOutput) IpAllowlist() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *User) pulumi.BoolPtrOutput { return v.IpAllowlist }).(pulumi.BoolPtrOutput)
}

// Indicates a user with super admininistrator privileges.
func (o UserOutput) IsAdmin() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.IsAdmin }).(pulumi.BoolOutput)
}

// Indicates if the user is a delegated administrator.
func (o UserOutput) IsDelegatedAdmin() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.IsDelegatedAdmin }).(pulumi.BoolOutput)
}

// Is 2-step verification enforced.
func (o UserOutput) IsEnforcedIn2StepVerification() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.IsEnforcedIn2StepVerification }).(pulumi.BoolOutput)
}

// Is enrolled in 2-step verification.
func (o UserOutput) IsEnrolledIn2StepVerification() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.IsEnrolledIn2StepVerification }).(pulumi.BoolOutput)
}

// Indicates if the user's Google mailbox is created. This property is only applicable if the user has been assigned a
// Gmail license.
func (o UserOutput) IsMailboxSetup() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.IsMailboxSetup }).(pulumi.BoolOutput)
}

// A list of the user's keywords. The maximum allowed data size is 1Kb.
func (o UserOutput) Keywords() UserKeywordArrayOutput {
	return o.ApplyT(func(v *User) UserKeywordArrayOutput { return v.Keywords }).(UserKeywordArrayOutput)
}

// A list of the user's languages. The maximum allowed data size is 1Kb.
func (o UserOutput) Languages() UserLanguageArrayOutput {
	return o.ApplyT(func(v *User) UserLanguageArrayOutput { return v.Languages }).(UserLanguageArrayOutput)
}

// The last time the user logged into the user's account. The value is in ISO 8601 date and time format. The time is the
// complete date plus hours, minutes, and seconds in the form YYYY-MM-DDThh:mm:ssTZD. For example,
// 2010-04-05T17:30:04+01:00.
func (o UserOutput) LastLoginTime() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.LastLoginTime }).(pulumi.StringOutput)
}

// A list of the user's locations. The maximum allowed data size is 10Kb.
func (o UserOutput) Locations() UserLocationArrayOutput {
	return o.ApplyT(func(v *User) UserLocationArrayOutput { return v.Locations }).(UserLocationArrayOutput)
}

// Holds the given and family names of the user, and the read-only fullName value. The maximum number of characters in the
// givenName and in the familyName values is 60. In addition, name values support unicode/UTF-8 characters, and can contain
// spaces, letters (a-z), numbers (0-9), dashes (-), forward slashes (/), and periods (.). Maximum allowed data size for
// this field is 1Kb.
func (o UserOutput) Name() UserNameOutput {
	return o.ApplyT(func(v *User) UserNameOutput { return v.Name }).(UserNameOutput)
}

// asps.list of the user's non-editable alias email addresses. These are typically outside the account's primary domain or
// sub-domain.
func (o UserOutput) NonEditableAliases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *User) pulumi.StringArrayOutput { return v.NonEditableAliases }).(pulumi.StringArrayOutput)
}

// The full path of the parent organization associated with the user. If the parent organization is the top-level, it is
// represented as a forward slash (/).
func (o UserOutput) OrgUnitPath() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.OrgUnitPath }).(pulumi.StringOutput)
}

// A list of organizations the user belongs to. The maximum allowed data size is 10Kb.
func (o UserOutput) Organizations() UserOrganizationArrayOutput {
	return o.ApplyT(func(v *User) UserOrganizationArrayOutput { return v.Organizations }).(UserOrganizationArrayOutput)
}

// Stores the password for the user account. A password can contain any combination of ASCII characters. A minimum of 8
// characters is required. The maximum length is 100 characters. As the API does not return the value of password, this
// field is write-only, and the value stored in the state will be what is provided in the configuration. The field is
// required on create and will be empty on import.
func (o UserOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

// A list of the user's phone numbers. The maximum allowed data size is 1Kb.
func (o UserOutput) Phones() UserPhoneArrayOutput {
	return o.ApplyT(func(v *User) UserPhoneArrayOutput { return v.Phones }).(UserPhoneArrayOutput)
}

// A list of POSIX account information for the user.
func (o UserOutput) PosixAccounts() UserPosixAccountArrayOutput {
	return o.ApplyT(func(v *User) UserPosixAccountArrayOutput { return v.PosixAccounts }).(UserPosixAccountArrayOutput)
}

// The user's primary email address. The primaryEmail must be unique and cannot be an alias of another user.
func (o UserOutput) PrimaryEmail() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.PrimaryEmail }).(pulumi.StringOutput)
}

// Recovery email of the user.
func (o UserOutput) RecoveryEmail() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.RecoveryEmail }).(pulumi.StringPtrOutput)
}

// Recovery phone of the user. The phone number must be in the E.164 format, starting with the plus sign (+). Example:
// +16506661212.
func (o UserOutput) RecoveryPhone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.RecoveryPhone }).(pulumi.StringPtrOutput)
}

// A list of the user's relationships to other users. The maximum allowed data size for this field is 2Kb.
func (o UserOutput) Relations() UserRelationArrayOutput {
	return o.ApplyT(func(v *User) UserRelationArrayOutput { return v.Relations }).(UserRelationArrayOutput)
}

// A list of SSH public keys. The maximum allowed data size is 10Kb.
func (o UserOutput) SshPublicKeys() UserSshPublicKeyArrayOutput {
	return o.ApplyT(func(v *User) UserSshPublicKeyArrayOutput { return v.SshPublicKeys }).(UserSshPublicKeyArrayOutput)
}

// Indicates if user is suspended.
func (o UserOutput) Suspended() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *User) pulumi.BoolPtrOutput { return v.Suspended }).(pulumi.BoolPtrOutput)
}

// Has the reason a user account is suspended either by the administrator or by Google at the time of suspension. The
// property is returned only if the suspended property is true.
func (o UserOutput) SuspensionReason() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.SuspensionReason }).(pulumi.StringOutput)
}

// ETag of the user's photo
func (o UserOutput) ThumbnailPhotoEtag() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.ThumbnailPhotoEtag }).(pulumi.StringOutput)
}

// Photo Url of the user.
func (o UserOutput) ThumbnailPhotoUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.ThumbnailPhotoUrl }).(pulumi.StringOutput)
}

// A list of the user's websites. The maximum allowed data size is 2Kb.
func (o UserOutput) Websites() UserWebsiteArrayOutput {
	return o.ApplyT(func(v *User) UserWebsiteArrayOutput { return v.Websites }).(UserWebsiteArrayOutput)
}

type UserArrayOutput struct{ *pulumi.OutputState }

func (UserArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*User)(nil)).Elem()
}

func (o UserArrayOutput) ToUserArrayOutput() UserArrayOutput {
	return o
}

func (o UserArrayOutput) ToUserArrayOutputWithContext(ctx context.Context) UserArrayOutput {
	return o
}

func (o UserArrayOutput) Index(i pulumi.IntInput) UserOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *User {
		return vs[0].([]*User)[vs[1].(int)]
	}).(UserOutput)
}

type UserMapOutput struct{ *pulumi.OutputState }

func (UserMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*User)(nil)).Elem()
}

func (o UserMapOutput) ToUserMapOutput() UserMapOutput {
	return o
}

func (o UserMapOutput) ToUserMapOutputWithContext(ctx context.Context) UserMapOutput {
	return o
}

func (o UserMapOutput) MapIndex(k pulumi.StringInput) UserOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *User {
		return vs[0].(map[string]*User)[vs[1].(string)]
	}).(UserOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserInput)(nil)).Elem(), &User{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserArrayInput)(nil)).Elem(), UserArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserMapInput)(nil)).Elem(), UserMap{})
	pulumi.RegisterOutputType(UserOutput{})
	pulumi.RegisterOutputType(UserArrayOutput{})
	pulumi.RegisterOutputType(UserMapOutput{})
}
