// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace.Inputs
{

    public sealed class GroupMembersMemberGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("deliverySettings")]
        public Input<string>? DeliverySettings { get; set; }

        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("role")]
        public Input<string>? Role { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public GroupMembersMemberGetArgs()
        {
        }
        public static new GroupMembersMemberGetArgs Empty => new GroupMembersMemberGetArgs();
    }
}
