// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace.Inputs
{

    public sealed class SchemaFieldNumericIndexingSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("maxValue")]
        public Input<double>? MaxValue { get; set; }

        [Input("minValue")]
        public Input<double>? MinValue { get; set; }

        public SchemaFieldNumericIndexingSpecArgs()
        {
        }
        public static new SchemaFieldNumericIndexingSpecArgs Empty => new SchemaFieldNumericIndexingSpecArgs();
    }
}
