// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace.Inputs
{

    public sealed class UserEmailArgs : global::Pulumi.ResourceArgs
    {
        [Input("address")]
        public Input<string>? Address { get; set; }

        [Input("customType")]
        public Input<string>? CustomType { get; set; }

        [Input("primary")]
        public Input<bool>? Primary { get; set; }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public UserEmailArgs()
        {
        }
        public static new UserEmailArgs Empty => new UserEmailArgs();
    }
}
