// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace.Inputs
{

    public sealed class UserImArgs : global::Pulumi.ResourceArgs
    {
        [Input("customProtocol")]
        public Input<string>? CustomProtocol { get; set; }

        [Input("customType")]
        public Input<string>? CustomType { get; set; }

        [Input("im")]
        public Input<string>? Im { get; set; }

        [Input("primary")]
        public Input<bool>? Primary { get; set; }

        [Input("protocol", required: true)]
        public Input<string> Protocol { get; set; } = null!;

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public UserImArgs()
        {
        }
        public static new UserImArgs Empty => new UserImArgs();
    }
}
