// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace.Inputs
{

    public sealed class UserPosixAccountGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        [Input("gecos")]
        public Input<string>? Gecos { get; set; }

        [Input("gid")]
        public Input<string>? Gid { get; set; }

        [Input("homeDirectory")]
        public Input<string>? HomeDirectory { get; set; }

        [Input("operatingSystemType")]
        public Input<string>? OperatingSystemType { get; set; }

        [Input("primary")]
        public Input<bool>? Primary { get; set; }

        [Input("shell")]
        public Input<string>? Shell { get; set; }

        [Input("systemId")]
        public Input<string>? SystemId { get; set; }

        [Input("uid")]
        public Input<string>? Uid { get; set; }

        [Input("username")]
        public Input<string>? Username { get; set; }

        public UserPosixAccountGetArgs()
        {
        }
        public static new UserPosixAccountGetArgs Empty => new UserPosixAccountGetArgs();
    }
}
